---
title: "Toronto Animal Services Requests and Complaints"
output: html_document
author: Reese Halfyard
abstract: In this paper I will uncover data about popular Cultural Hotspots in 2021 across Toronto among their 6 boroughs; Scarborough, York, East York, North York, Etobicoke, and Old Toronto. Data has been collected from Open Data Toronto, and updated in January of 2022. 
---

```{r}

# install.packages("opendatatoronto")
### workspace setup ###
library(tidyverse)
library(opendatatoronto)
library(dplyr)

# get package
package <- show_package("c7be2ee7-d317-4a28-8cbe-bff1ce116b46")
package
 
# get all resources for this package
resources <- list_package_resources("c7be2ee7-d317-4a28-8cbe-bff1ce116b46")
 
# identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))
 
# load the first datastore resource as a sample
data <- filter(datastore_resources, row_number()==1) %>% get_resource()
data
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

